import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: { DEFAULT: "1rem", sm: "1.5rem", lg: "2rem" },
      screens: { "2xl": "1400px" },
    },
    extend: {
      // All colors reference CSS custom properties set by admin
      colors: {
        primary: {
          DEFAULT: "var(--color-primary)",
          dark: "var(--color-primary-dark)",
          light: "var(--color-primary-light)",
          50: "var(--color-primary-50)",
        },
        gold: {
          DEFAULT: "var(--color-gold)",
          light: "var(--color-gold-light)",
          dark: "var(--color-gold-dark)",
        },
        ivory: "var(--color-ivory)",
        cream: "var(--color-cream)",
        parchment: "var(--color-parchment)",
        sand: "var(--color-sand)",
        text: {
          primary: "var(--color-text-primary)",
          secondary: "var(--color-text-secondary)",
          muted: "var(--color-text-muted)",
          disabled: "var(--color-text-disabled)",
          inverse: "var(--color-text-inverse)",
        },
        success: { DEFAULT: "var(--color-success)", bg: "var(--color-success-bg)" },
        error: { DEFAULT: "var(--color-error)", bg: "var(--color-error-bg)" },
        warning: { DEFAULT: "var(--color-warning)", bg: "var(--color-warning-bg)" },
        border: "var(--color-border)",
        input: "var(--color-border)",
        ring: "var(--color-primary)",
        background: "var(--color-ivory)",
        foreground: "var(--color-text-primary)",
      },
      // Font families reference CSS custom properties set by admin
      fontFamily: {
        heading: "var(--font-heading)",
        body: "var(--font-body)",
        accent: "var(--font-accent)",
        sans: "var(--font-body)",
        serif: "var(--font-heading)",
      },
      // Font sizes reference CSS custom properties set by admin
      fontSize: {
        display: ["var(--text-display)", { lineHeight: "1.1", letterSpacing: "-0.02em" }],
        h1: ["var(--text-h1)", { lineHeight: "1.15", letterSpacing: "-0.01em" }],
        h2: ["var(--text-h2)", { lineHeight: "1.2" }],
        h3: ["var(--text-h3)", { lineHeight: "1.25" }],
        h4: ["var(--text-h4)", { lineHeight: "1.3" }],
        h5: ["var(--text-h5)", { lineHeight: "1.35" }],
        "body-xl": ["var(--text-body-xl)", { lineHeight: "1.6" }],
        "body-base": ["var(--text-body)", { lineHeight: "1.6" }],
        "body-sm": ["var(--text-sm)", { lineHeight: "1.5" }],
        caption: ["var(--text-xs)", { lineHeight: "1.4", letterSpacing: "0.08em" }],
        price: ["var(--text-price)", { lineHeight: "1.2" }],
        "price-sm": ["var(--text-price-sm)", { lineHeight: "1.2" }],
      },
      spacing: {
        "4.5": "1.125rem",
        "13":  "3.25rem",
        "15":  "3.75rem",
        "18":  "4.5rem",
        "22":  "5.5rem",
        "88":  "22rem",
        "100": "25rem",
        "112": "28rem",
        "128": "32rem",
      },
      borderRadius: {
        xs: "2px",
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "20px",
        "2xl": "28px",
      },
      boxShadow: {
        xs: "0 1px 3px rgba(28,20,16,0.06)",
        sm: "0 2px 8px rgba(28,20,16,0.08)",
        md: "0 4px 16px rgba(28,20,16,0.10)",
        lg: "0 8px 32px rgba(28,20,16,0.12)",
        xl: "0 16px 48px rgba(28,20,16,0.15)",
        gold: "0 0 0 2px var(--color-gold)",
        "gold-sm": "0 0 0 1px var(--color-gold)",
        inner: "inset 0 2px 8px rgba(28,20,16,0.06)",
      },
      transitionDuration: {
        fast: "150ms",
        normal: "250ms",
        slow: "400ms",
        slower: "600ms",
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.34,1.56,0.64,1)",
        "ease-in-soft": "cubic-bezier(0.4,0,1,1)",
        "ease-out-soft": "cubic-bezier(0.0,0,0.2,1)",
        premium: "cubic-bezier(0.22,1,0.36,1)",
      },
      keyframes: {
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "fade-up": { from: { opacity: "0", transform: "translateY(16px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "slide-in-right": { from: { transform: "translateX(100%)" }, to: { transform: "translateX(0)" } },
        "slide-in-left": { from: { transform: "translateX(-100%)" }, to: { transform: "translateX(0)" } },
        "slide-up": { from: { transform: "translateY(100%)" }, to: { transform: "translateY(0)" } },
        shimmer: { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "scale-in": { from: { opacity: "0", transform: "scale(0.95)" }, to: { opacity: "1", transform: "scale(1)" } },
        "spin-slow": { to: { transform: "rotate(360deg)" } },
        "slide-down": {
          from: { opacity: "0", transform: "translateY(-6px)" },
          to:   { opacity: "1", transform: "translateY(0)" },
        },
        shine: {
          "0%":   { transform: "translateX(-150%) skewX(-20deg)", opacity: "0" },
          "15%":  { opacity: "0.7" },
          "100%": { transform: "translateX(150%) skewX(-20deg)", opacity: "0" },
        },
        "pulse-soft": {
          "0%, 100%": { transform: "scale(1)", opacity: "1" },
          "50%":      { transform: "scale(1.06)", opacity: "0.85" },
        },
        ripple: {
          "0%":   { transform: "scale(0)", opacity: "0.45" },
          "100%": { transform: "scale(2.8)", opacity: "0" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.25s ease-out",
        "fade-up": "fade-up 0.35s ease-out",
        "slide-in-right": "slide-in-right 0.3s cubic-bezier(0.0,0,0.2,1)",
        "slide-in-left": "slide-in-left 0.3s cubic-bezier(0.0,0,0.2,1)",
        "slide-up": "slide-up 0.3s cubic-bezier(0.0,0,0.2,1)",
        "slide-down": "slide-down 0.2s ease-out",
        shimmer: "shimmer 1.5s infinite linear",
        "scale-in": "scale-in 0.2s ease-out",
        "spin-slow": "spin-slow 2s linear infinite",
        shine: "shine 1.1s cubic-bezier(0.22,1,0.36,1)",
        "pulse-soft": "pulse-soft 2.8s cubic-bezier(0.4,0,0.6,1) infinite",
        ripple: "ripple 0.6s cubic-bezier(0.22,1,0.36,1) forwards",
      },
      backgroundImage: {
        shimmer: "linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.4) 50%, transparent 100%)",
        "gold-gradient": "linear-gradient(135deg, var(--color-gold-dark), var(--color-gold), var(--color-gold-light))",
        "primary-gradient": "linear-gradient(135deg, var(--color-primary-dark), var(--color-primary))",
        "ivory-gradient": "linear-gradient(180deg, var(--color-ivory), var(--color-cream))",
      },
    },
  },
  plugins: [],
};

export default config;
